export const USER_PROFILE_DETAILS_REQUEST = "USER.PROFILE_DETAILS_REQUEST";
export const USER_PROFILE_DETAILS_SUCCESS = "USER.PROFILE_DETAILS_SUCCESS";
export const USER_PROFILE_DETAILS_FAIL = "USER.PROFILE_DETAILS_FAIL";
export const USER_PROFILE_DETAILS_RESET = "USER.PROFILE_DETAILS_RESET";

export const USER_UPDATE_PROFILE_REQUEST = "USER.UPDATE_PROFILE_REQUEST";
export const USER_UPDATE_PROFILE_SUCCESS = "USER.UPDATE_PROFILE_SUCCESS";
export const USER_UPDATE_PROFILE_FAIL = "USER.UPDATE_PROFILE_FAIL";
export const USER_UPDATE_PROFILE_RESET = "USER.UPDATE_PROFILE_RESET";

export const USERS_LIST_REQUEST = "USERS.LIST_REQUEST";
export const USERS_LIST_SUCCESS = "USERS.LIST_SUCCESS";
export const USERS_LIST_FAIL = "USERS.LIST_FAIL";

export const USER_FOLLOW_REQUEST = "USER.FOLLOW_REQUEST";
export const USER_FOLLOW_SUCCESS = "USER.FOLLOW_SUCCESS";
export const USER_FOLLOW_FAIL = "USER.FOLLOW_FAIL";

export const USER_UNFOLLOW_REQUEST = "USER.UNFOLLOW_REQUEST";
export const USER_UNFOLLOW_SUCCESS = "USER.UNFOLLOW_SUCCESS";
export const USER_UNFOLLOW_FAIL = "USER.UNFOLLOW_FAIL";