export const USER_PROFILE_DETAILS_REQUEST = "USER.PROFILE_DETAILS_REQUEST";
export const USER_PROFILE_DETAILS_SUCCESS = "USER.PROFILE_DETAILS_SUCCESS";
export const USER_PROFILE_DETAILS_FAIL = "USER.PROFILE_DETAILS_FAIL";
export const USER_PROFILE_DETAILS_RESET = "USER.PROFILE_DETAILS_RESET";

export const USER_UPDATE_PROFILE_REQUEST = "USER.UPDATE_PROFILE_REQUEST";
export const USER_UPDATE_PROFILE_SUCCESS = "USER.UPDATE_PROFILE_SUCCESS";
export const USER_UPDATE_PROFILE_FAIL = "USER.UPDATE_PROFILE_FAIL";
export const USER_UPDATE_PROFILE_RESET = "USER.UPDATE_PROFILE_RESET";

export const USERS_LIST_REQUEST = "USERS.LIST_REQUEST";
export const USERS_LIST_SUCCESS = "USERS.LIST_SUCCESS";
export const USERS_LIST_FAIL = "USERS.LIST_FAIL";
export const USERS_LIST_RESET = "USERS.LIST_RESET";

export const USER_FOLLOW_REQUEST = "USER.FOLLOW_REQUEST";
export const USER_FOLLOW_SUCCESS = "USER.FOLLOW_SUCCESS";
export const USER_FOLLOW_FAIL = "USER.FOLLOW_FAIL";

export const USER_UNFOLLOW_REQUEST = "USER.UNFOLLOW_REQUEST";
export const USER_UNFOLLOW_SUCCESS = "USER.UNFOLLOW_SUCCESS";
export const USER_UNFOLLOW_FAIL = "USER.UNFOLLOW_FAIL";

export const USER_LIKE_REQUEST = "USER.LIKE_REQUEST";
export const USER_LIKE_SUCCESS = "USER.LIKE_SUCCESS";
export const USER_LIKE_FAIL = "USER.LIKE_FAIL";

export const USER_DISLIKE_REQUEST = "USER.DISLIKE_REQUEST";
export const USER_DISLIKE_SUCCESS = "USER.DISLIKE_SUCCESS";
export const USER_DISLIKE_FAIL = "USER.DISLIKE_FAIL";

export const USERS_FRIENDS_LIST_REQUEST = "USERS.FRIENDS_LIST_REQUEST";
export const USERS_FRIENDS_LIST_SUCCESS = "USERS.FRIENDS_LIST_SUCCESS";
export const USERS_FRIENDS_LIST_FAIL = "USERS.FRIENDS_LIST_FAIL";
export const USERS_FRIENDS_LIST_RESET = "USERS.FRIENDS_LIST_RESET";